# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 08:20
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bimagesmall',
            field=django_resized.forms.ResizedImageField(blank=True, editable=False, upload_to='books_image_small/'),
        ),
    ]
