# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_book', '0002_auto_20170327_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='bimagelarge',
            new_name='bimage',
        ),
        migrations.RemoveField(
            model_name='books',
            name='bimagesmall',
        ),
    ]
