# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bcdateadd',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bimagelarge',
            field=models.ImageField(upload_to='books_image_large/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bimagesmall',
            field=models.ImageField(blank=True, editable=False, upload_to='books_image_small/'),
        ),
    ]
