# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170105_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='bauthor',
        ),
        migrations.RemoveField(
            model_name='books',
            name='bcategories',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Books_Author',
        ),
        migrations.DeleteModel(
            name='Books_Categories',
        ),
    ]
